@startuml
class Consts {
    + <<const>> DEFAULT_TIME_TO_REPRODUCE : int = 6
    + <<const>> DEFAULT_NUM_PREY : int = 150
    + <<const>> DEFAULT_NUM_OBSTACLES : int = 75
    + <<const>> DEFAULT_NUM_PREDATORS : int = 20
    + <<const>> DEFAULT_TIME_TO_FEED : int = 6
    + <<const>> OCEAN_NUM_ROWS : int = 25
    + <<const>> OCEAN_NUM_COLS : int = 70
    + <<const>> OCEAN_ITERATION : int = 1000
}
@enduml
