@startuml
class Publisher {
    + Subscribe(handler:NewIterationDelegate) : void
    + Unsubscribe(handler:NewIterationDelegate) : void
    + Publisher(iterationCount:int)
    + Run() : void
}
@enduml
