@startuml
class Subscriber {
    + Subscriber(s:SortDoubleArray)
    + ExchangeCount : ulong <<get>>
    + SwapCount : ulong <<get>>
    + CalcExchnageCount(sender:object, iteration:int) : void
    + CalcSwapsCount(sender:object, iteration:int) : void
    + GetStartTime(sender:object, time:DateTime) : void
    + GetFinishTime(sender:object, time:DateTime) : void
    + CalcDiffStartFinishTime() : TimeSpan
}
Subscriber --> "StartTime" DateTime
Subscriber --> "FinishTime" DateTime
@enduml
