@startuml
!include ./20240823_Lesson_Publisher/NewiterationEventArgs.puml
!include ./20240823_Lesson_Publisher/Subscriber.puml
!include ./20240823_Lesson_Publisher/SubscriberEventArgs.puml
!include ./20240823_Lesson_Publisher/SubscriberEvent.puml
!include ./20240823_Lesson_Publisher/Publisher.puml
!include ./20240823_Lesson_Publisher/PublisherEvent.puml
!include ./20240823_Lesson_Publisher/PublisherEventArgs.puml
!include ./20240823_Lesson_Publisher/NewIterationDelegate.puml
!include ./20240823_Lesson_Publisher/Program.puml
!include ./test/Program.puml
!include ./20240823_HW_Delegate/InsertSort.puml
!include ./20240823_HW_Delegate/QuickSort.puml
!include ./20240823_HW_Delegate/Subscriber.puml
!include ./20240823_HW_Delegate/SortDoubleArray.puml
!include ./20240823_HW_Delegate/BubbleSort.puml
!include ./20240823_HW_Delegate/IterationDateTimeDelegate.puml
!include ./20240823_HW_Delegate/Program.puml
!include ./OceanLife/UI.puml
!include ./OceanLife/Game.puml
!include ./OceanLife/Cell.puml
!include ./OceanLife/BL.puml
!include ./OceanLife/Consts.puml
!include ./OceanLife/Movement.puml
!include ./OceanLife/Image.puml
!include ./OceanLife/Coordinates.puml
!include ./OceanLife/Obstacle.puml
!include ./OceanLife/Ocean.puml
!include ./OceanLife/Program.puml
!include ./Library/Generate1dArray/Generate1dArray.puml
!include ./Library/Generate1dArray/GenerateDouble1dArray.puml
!include ./OceanLife/Animals/Prey.puml
!include ./OceanLife/Animals/Predator.puml
!include ./OceanLife/Interfaces/IShowKill.puml
!include ./20240823_Lesson_Publisher/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./20240823_Lesson_Publisher/obj/Debug/net8.0/20240823_Lesson_Publisher.GlobalUsings.g.puml
!include ./20240823_Lesson_Publisher/obj/Debug/net8.0/20240823_Lesson_Publisher.AssemblyInfo.puml
!include ./20240823_HW_Delegate/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./20240823_HW_Delegate/obj/Debug/net8.0/20240823_HW_Delegate.AssemblyInfo.puml
!include ./20240823_HW_Delegate/obj/Debug/net8.0/20240823_HW_Delegate.GlobalUsings.g.puml
!include ./OceanLife/obj/Debug/net8.0/OceanLife.GlobalUsings.g.puml
!include ./OceanLife/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./OceanLife/obj/Debug/net8.0/OceanLife.AssemblyInfo.puml
!include ./Library/Generate1dArray/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Library/Generate1dArray/obj/Debug/net8.0/Generate1dArray.GlobalUsings.g.puml
!include ./Library/Generate1dArray/obj/Debug/net8.0/GenerateArray.AssemblyInfo.puml
!include ./Library/Generate1dArray/obj/Debug/net8.0/Generate1dArray.AssemblyInfo.puml
!include ./Library/Generate1dArray/obj/Debug/net8.0/GenerateArray.GlobalUsings.g.puml
@enduml
